// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ9BmGVNgr-Aa9uCuGuL29OyzmIVXb-4k',
    appId: '1:1005737972217:android:96a8a674408ebc6c852d28',
    messagingSenderId: '1005737972217',
    projectId: 'instagram-clone-course-polina',
    storageBucket: 'instagram-clone-course-polina.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhS3Q28R4HX8EHZUDtcHipYbA5d64xdvc',
    appId: '1:1005737972217:ios:496b0f5686e9c3de852d28',
    messagingSenderId: '1005737972217',
    projectId: 'instagram-clone-course-polina',
    storageBucket: 'instagram-clone-course-polina.appspot.com',
    androidClientId: '1005737972217-uge47d9idf9drm6cpg1jkobjuv1th5es.apps.googleusercontent.com',
    iosClientId: '1005737972217-7ugc76qftk8ma3qfbdllaon4kiudp6l4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstProject',
  );
}
